### ISSUE TITLE
Actividad 8 Hilos en Consola 

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-team-ola#1]
[actividad.8.hilos.prueba.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-team-ola/files/15133202/actividad.8.hilos.prueba.pdf)

(Reporte actividad 8)

**Comment by Kim-Mendoza3** [comment]
calificacion 18.5

**Comment by josealfredo79** [comment]
bien hecho y revisado...
